### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by dorris09** [Virtual-Protocol/agent-contributions-library#110]
C:\Users\COMPLAB>git clone https://github.com/your-username/agent-contributions-library.git
Cloning into 'agent-contributions-library'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/your-username/agent-contributions-library.git/' not found

**Comment by dorris09** [comment]
C:\Users\COMPLAB>git clone https://github.com/dorris09/virtuals-protocol-acl.git
Cloning into 'virtuals-protocol-acl'...
remote: Enumerating objects: 3996, done.
remote: Counting objects: 100% (444/444), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 3996 (delta 386), reused 277 (delta 277), pack-reused 3552 (from 1)
Receiving objects: 100% (3996/3996), 1.67 GiB | 4.19 MiB/s, done.
Resolving deltas: 100% (734/734), done.

C:\Users\COMPLAB>cd agent-contributions-library
The system cannot find the path specified.

**Comment by armlynobinguar** [comment]
Please download the zip file instead. 

<img width="1340" alt="Screenshot 2024-09-02 at 2 58 22 PM" src="https://github.com/user-attachments/assets/0efb1de6-8122-423d-8f4d-aa91cada615b">

**Comment by armlynobinguar** [comment]
Once you downloaded the zip file. You'll be able to have a copy and click that file to unzip

<img width="383" alt="Screenshot 2024-09-02 at 2 59 53 PM" src="https://github.com/user-attachments/assets/eacab40e-e5cb-4f92-8634-9766ba351ffc">

**Comment by armlynobinguar** [comment]
Once the file is downloaded and unzip the file, open your vscode and click this. 

<img width="1490" alt="Screenshot 2024-09-02 at 3 07 55 PM" src="https://github.com/user-attachments/assets/b02e61cb-1a30-42ba-8cef-0538133a8c91">

**Comment by armlynobinguar** [comment]
<img width="1490" alt="Screenshot 2024-09-02 at 3 08 02 PM" src="https://github.com/user-attachments/assets/b909d244-ce01-4ee1-ac15-941d52daf4c4">

The look should be like this

**Comment by dorris09** [comment]
I'm using colab.

**Comment by armlynobinguar** [comment]
When submitting your dataset, we will use vscode for git. Collab is for you to scrape the website.

**Comment by dorris09** [comment]
![image](https://github.com/user-attachments/assets/6771fa74-f3b6-415f-b137-01d0a585296c)

**Comment by dorris09** [comment]
![image](https://github.com/user-attachments/assets/019e5bae-a709-44e5-bb6d-5873a7ac2756)

**Comment by dorris09** [comment]
Teach, how can I transfer the code from colab to vscode?

**Comment by armlynobinguar** [comment]
No need na po siya ilagay sa vscode, kapag may dataset na po kayo na output. Iyon lang po ilalagay sa vscode
