### ISSUE TITLE
regarding pull request

### ISSUE THREAD

**Issue by TalhaPirzada** [Virtual-Protocol/agent-contributions-library#127]
![image](https://github.com/user-attachments/assets/c692e5b7-5921-4014-b8d4-8169f84c947c)
  how can  i  do pull request?

**Comment by armlynobinguar** [comment]
Fork the repo and make sure to follow this: https://github.com/Virtual-Protocol/agent-contributions-library/discussions/105

**Comment by armlynobinguar** [comment]
@TalhaPirzada is this resolved already?
