### ISSUE TITLE
Unable to push my dataset for Act 2 

### ISSUE THREAD

**Issue by VanTheDamned** [Virtual-Protocol/agent-contributions-library#211]
![error](https://github.com/user-attachments/assets/0430fffa-3b11-4403-8c0a-e3f5ee7b8f47)

**Comment by armlynobinguar** [comment]
git pull first before doing git push

**Comment by VanTheDamned** [comment]
already did din po

![image](https://github.com/user-attachments/assets/ca18eed3-6c07-42ad-bb31-c70138a383e8)

**Comment by VanTheDamned** [comment]
merge failed

**Comment by armlynobinguar** [comment]
https://drive.google.com/drive/u/3/folders/1Jhna_WOj5F0bPruJSjdHQDtg4rG0kB1-

Can you check this?

**Comment by VanTheDamned** [comment]
I already fixed it. I just added another branch and sync it. Thank you!

**Comment by VanTheDamned** [comment]
Setting this issue as fixed.
