### ISSUE TITLE
Can't resubmit the Act3 due to this error

### ISSUE THREAD

**Issue by VanTheDamned** [Virtual-Protocol/agent-contributions-library#236]
![image](https://github.com/user-attachments/assets/8e8cd09e-4e89-4e58-8c27-edbfab71c957)

**Comment by armlynobinguar** [comment]
Have you watched the recordings? Ive added another alternative there to upload

**Comment by armlynobinguar** [comment]
https://drive.google.com/drive/u/3/folders/1Jhna_WOj5F0bPruJSjdHQDtg4rG0kB1-

**Comment by VanTheDamned** [comment]
Nafix ko na po using the alternative way, Thanks po.
